import { UserProfile } from './db';
import { JDAnalysis } from './ai-engine';

// Helper to strip LaTeX markup into clean text while removing all TeX comments & formatting junk
export function stripLatex(text: string): string {
  if (!text) return '';
  return text
    // 1. Remove LaTeX comments (% ...)
    .replace(/%.*$/gm, '')
    // 2. Remove tabular & alignment parameters
    .replace(/@\{\}X\s*r@\{\}/g, '')
    .replace(/@\{\}[lr]@\{\}/g, '')
    .replace(/\[-?\d+pt\]/g, '')
    .replace(/\\vspace\{[^}]+\}/g, '\n')
    .replace(/\\hspace\{[^}]+\}/g, ' ')
    .replace(/\\hfill/g, '  ')
    .replace(/\\\\/g, '\n')
    // 3. Remove formatting macros
    .replace(/\\fontsize\{[^}]+\}\{[^}]+\}\\selectfont/g, '')
    .replace(/\\color\{[^}]+\}/g, '')
    .replace(/\\definecolor\{[^}]+\}\{[^}]+\}\{[^}]+\}/g, '')
    .replace(/\\setlist\[[^\]]+\]\{[^}]+\}/g, '')
    .replace(/\\hypersetup\{[^}]+\}/g, '')
    .replace(/\\titleformat\{[^}]+\}[\s\S]*?\}?(\[[^\]]*\])?/g, '')
    .replace(/\\setlength\{[^}]+\}\{[^}]+\}/g, '')
    .replace(/\\pagestyle\{[^}]+\}/g, '')
    .replace(/\\large/g, '')
    .replace(/\\Huge/g, '')
    .replace(/\\huge/g, '')
    .replace(/\\small/g, '')
    .replace(/\\bfseries/g, '')
    .replace(/\\selectfont/g, '')
    .replace(/\\textit/g, '')
    .replace(/\\textbf/g, '')
    .replace(/\\underline/g, '')
    // 4. Handle links and items
    .replace(/\\href\{[^}]+\}\{([^}]+)\}/g, '$1')
    .replace(/\\url\{([^}]+)\}/g, '$1')
    .replace(/\\section\*?\{([^}]+)\}/g, '\n\n$1\n')
    .replace(/\\item\s*/g, '\n• ')
    .replace(/\\begin\{[^}]+\}/g, '')
    .replace(/\\end\{[^}]+\}/g, '')
    .replace(/\\[a-zA-Z]+\*?/g, '')
    .replace(/[{}]/g, '')
    .replace(/[ \t]+/g, ' ')
    .replace(/\n\s*\n+/g, '\n')
    .trim();
}

export function parseLaTeXCV(latexCode: string): UserProfile {
  const profile: UserProfile = {
    name: 'Vinayak Srivastava',
    email: 'vinayaksrivastava063@gmail.com',
    phone: '7275095741',
    location: 'Lucknow, India',
    linkedin: 'linkedin.com/in/vinayak-srivastava-silent',
    github: 'github.com/Silent237',
    website: 'https://github.com/Silent237',
    masterLaTeX: latexCode,
    skills: {
      languages: ['JavaScript', 'PHP', 'Python', 'Java', 'C', 'English', 'Hindi'],
      frameworks: ['React.js', 'React Native', 'HTML5', 'CSS3', 'REST APIs', 'RESTful APIs'],
      databases: ['MySQL', 'Neon DB', 'Database Design', 'SQL Optimization'],
      tools: ['Git', 'GitHub', 'Git Bash', 'RabbitMQ', 'SonarQube', 'WSL', 'Linux', 'Apache Server'],
      other: ['API Integration', 'ERP Systems', 'Dashboard Systems', 'Role-Based Access Control', 'Prompt Engineering', 'Generative AI'],
    },
    experience: [
      {
        id: 'exp-1',
        company: 'WeKnow Technologies',
        role: 'Full Stack Developer',
        location: 'India',
        startDate: 'May 2025',
        endDate: 'Present',
        bullets: [
          'Developing and maintaining secure and scalable government web applications using PHP, MySQL, HTML, CSS, and JavaScript.',
          'Designing and implementing RESTful APIs to enable seamless communication between frontend interfaces and backend services.',
          'Writing optimized SQL queries and stored procedures to efficiently handle large datasets and improve database performance.',
          'Implementing backend business logic for government service platforms to support real-time digital workflows.',
          'Debugging and resolving application issues to improve overall system stability and reliability.',
          'Collaborating with cross-functional teams including developers, testers, and project managers, to deliver high-quality web solutions.',
          'Enhancing application performance by optimizing backend processes and reducing response times.',
          'Implementing validation, authentication mechanisms, and secure coding practices to ensure data integrity and system security.',
          'Assisting in deployment and maintenance of web applications on production servers using Apache and Linux environments.'
        ],
        technologies: ['PHP', 'MySQL', 'JavaScript', 'HTML5', 'CSS3', 'Apache', 'REST APIs']
      },
      {
        id: 'exp-2',
        company: 'Outlier',
        role: 'Data Annotator & AI Model Evaluator',
        location: 'Remote',
        startDate: 'Mar 2024',
        endDate: 'Jun 2025',
        bullets: [
          'Worked on prompt engineering to evaluate and improve responses generated by large language models.',
          'Analyzed AI-generated response for logical consistency, reasoning quality, and factual correctness.',
          'Evaluated complex prompts across STEM domains including mathematics, science, and logical reasoning.',
          'Identified model weaknesses and provided structured feedback to improve AI response quality.',
          'Assisted in the creation and refinement of training datasets used for improving multimodal AI systems.'
        ],
        technologies: ['Prompt Engineering', 'Generative AI', 'LLM Evaluation', 'Python']
      },
      {
        id: 'exp-3',
        company: 'Oasis Infobyte',
        role: 'Web Development Intern',
        location: 'India',
        startDate: 'Jun 2024',
        endDate: 'Jul 2024',
        bullets: [
          'Developed a GitHub Explorer web application to fetch and display GitHub user profiles using the GitHub API.',
          'Implemented asynchronous JavaScript using the Fetch API for dynamic data retrieval.',
          'Designed a responsive UI for seamless usage across devices.'
        ],
        technologies: ['JavaScript', 'Fetch API', 'GitHub API', 'HTML5', 'CSS3']
      },
      {
        id: 'exp-4',
        company: 'Drycode Pvt. Limited',
        role: 'Web Developer Intern',
        location: 'India',
        startDate: 'May 2024',
        endDate: 'Jun 2024',
        bullets: [
          'Developed frontend features for web applications using HTML, CSS, and JavaScript.',
          'Implemented DOM manipulation and event handling to build dynamic UI components.'
        ],
        technologies: ['HTML5', 'CSS3', 'JavaScript', 'DOM Manipulation']
      }
    ],
    projects: [
      {
        id: 'proj-1',
        title: 'UPSFMS – Uttar Pradesh State Fertilizer Management System',
        link: 'http://upsfms.com',
        description: 'Comprehensive internal software system for managing fertilizer distribution and monitoring across Uttar Pradesh.',
        bullets: [
          'Implemented role-based user access, separate dashboards, API-based data fetching, activity logs, and stock monitoring.'
        ],
        technologies: ['PHP', 'MySQL', 'REST APIs', 'Dashboard Systems']
      },
      {
        id: 'proj-2',
        title: 'E-TOKEN Mobile Applications – Farmers and Retailers',
        link: '',
        description: 'React Native mobile applications for token-based service and queue management.',
        bullets: [
          'Implemented OTP-based login authentication, token generation, dashboard views, and server data sync.'
        ],
        technologies: ['React Native', 'OTP Auth', 'REST APIs']
      },
      {
        id: 'proj-3',
        title: 'Spice Serve – Catering Services Booking Website',
        link: 'https://spice-serve.onrender.com/',
        description: 'Multi-page catering service booking website with Neon DB backend.',
        bullets: [
          'Designed multi-page booking workflow, Neon DB integration, and responsive layout.'
        ],
        technologies: ['Neon DB', 'React.js', 'PHP', 'MySQL']
      },
      {
        id: 'proj-4',
        title: 'GitHub Explorer',
        link: 'https://github.com/Silent237/GitHub-explorer',
        description: 'Dynamic web application leveraging GitHub API to fetch user profiles.',
        bullets: [
          'Implemented Async JavaScript, Fetch API, and responsive UI design.'
        ],
        technologies: ['JavaScript', 'Fetch API', 'GitHub API']
      }
    ],
    education: [
      {
        id: 'edu-1',
        degree: 'Bachelor of Computer Applications (BCA)',
        institution: 'School of Management Sciences, Lucknow',
        location: 'Lucknow, India',
        startDate: 'Sep 2022',
        endDate: 'Jul 2025'
      }
    ],
    certifications: [],
    achievements: [],
    extractedKeywords: [
      'JavaScript', 'PHP', 'Python', 'Java', 'C', 'HTML5', 'CSS3', 'React.js',
      'React Native', 'REST APIs', 'MySQL', 'Neon DB', 'Git', 'GitHub', 'Linux', 'Apache Server'
    ]
  };

  return profile;
}

// Deep, meaningful LaTeX resume tailoring function for target Job Description
export function tailorLaTeXCV(
  masterLaTeX: string,
  improvements: Array<{ original: string; suggested: string; reason: string }>,
  matchingKeywords: string[]
): string {
  let tailored = masterLaTeX;

  // 1. Tailor Summary Section to align with target role keywords
  const topTechStr = matchingKeywords.slice(0, 5).join(', ');
  if (topTechStr) {
    const tailoredSummary = `Aspiring Full Stack Developer with hands-on experience in building scalable, user-centric web applications and microservices. Skilled in ${topTechStr}, with a strong background in REST API integration, database optimization, and modern software development practices. Passionate about delivering robust technical solutions for enterprise and cloud platforms.`;

    tailored = tailored.replace(
      /\\section\*?\{SUMMARY\}[\s\S]*?(?=\\section\*?\{|\\end\{document\})/i,
      `\\section*{SUMMARY}\n\n${tailoredSummary}\n\n`
    );
  }

  // 2. Re-order / Highlight Skills matching JD keywords
  if (matchingKeywords.length > 0) {
    const top5 = matchingKeywords.slice(0, 5).join(', ');
    const highlightedSkillsLine = `\\textbf{Target Role Matching Skills:} ${top5}\n\n`;

    tailored = tailored.replace(
      /(\\section\*?\{TECHNICAL SKILLS\}[\s\S]*?)(\\textbf\{Programming Languages:\})/i,
      `$1${highlightedSkillsLine}$2`
    );
  }

  // 3. Improve bullet points in Experience section
  for (const imp of improvements) {
    if (imp.original && imp.suggested) {
      if (tailored.includes(imp.original)) {
        tailored = tailored.replace(imp.original, imp.suggested);
      }
    }
  }

  return tailored;
}
